apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportify
  labels:
    app: reportify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reportify
  template:
    metadata:
      labels:
        app: reportify
    spec:
      containers:
        - name: reportify
          image: 590183651344.dkr.ecr.eu-west-1.amazonaws.com/reportify:latest
          ports:
            - containerPort: 8080
